// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCsb-3zc832V2wcjNkTrwtnmdjWsj9sM',
    appId: '1:491209077299:web:948a1e3cc37dcda2766946',
    messagingSenderId: '491209077299',
    projectId: 'workspace-64c3a',
    authDomain: 'workspace-64c3a.firebaseapp.com',
    storageBucket: 'workspace-64c3a.firebasestorage.app',
    measurementId: 'G-N1C2R9PXKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlBgn3yqebDzePquBbtq8J_A4S1jMGRCU',
    appId: '1:491209077299:android:5ecaf1cf5b417ca5766946',
    messagingSenderId: '491209077299',
    projectId: 'workspace-64c3a',
    storageBucket: 'workspace-64c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcbZ1mcbpqjbvSmw2Nsdc5u_VdCdIhCxk',
    appId: '1:491209077299:ios:e200eabe62fec374766946',
    messagingSenderId: '491209077299',
    projectId: 'workspace-64c3a',
    storageBucket: 'workspace-64c3a.firebasestorage.app',
    iosBundleId: 'com.example.workspaceIeee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcbZ1mcbpqjbvSmw2Nsdc5u_VdCdIhCxk',
    appId: '1:491209077299:ios:e200eabe62fec374766946',
    messagingSenderId: '491209077299',
    projectId: 'workspace-64c3a',
    storageBucket: 'workspace-64c3a.firebasestorage.app',
    iosBundleId: 'com.example.workspaceIeee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrCsb-3zc832V2wcjNkTrwtnmdjWsj9sM',
    appId: '1:491209077299:web:14849caa02aad3e9766946',
    messagingSenderId: '491209077299',
    projectId: 'workspace-64c3a',
    authDomain: 'workspace-64c3a.firebaseapp.com',
    storageBucket: 'workspace-64c3a.firebasestorage.app',
    measurementId: 'G-XH41SY04K0',
  );
}
